// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppendImageOperation(arg1:main.ImageOperation):Promise<boolean>;

export function OpenImageFileSelector():Promise<boolean>;

export function ProcessImage():Promise<main.ProcessedImage>;
