// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddImageOperation(arg1) {
  return window['go']['main']['App']['AddImageOperation'](arg1);
}

export function OpenImageFileSelector() {
  return window['go']['main']['App']['OpenImageFileSelector']();
}

export function ProccessImage() {
  return window['go']['main']['App']['ProccessImage']();
}
