// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendImageOperation(arg1) {
  return window['go']['main']['App']['AppendImageOperation'](arg1);
}

export function GetUserSelectedProjectFileContent() {
  return window['go']['main']['App']['GetUserSelectedProjectFileContent']();
}

export function MirrorImageHorizontally() {
  return window['go']['main']['App']['MirrorImageHorizontally']();
}

export function MirrorImageVertically() {
  return window['go']['main']['App']['MirrorImageVertically']();
}

export function MoveImageOperation(arg1, arg2) {
  return window['go']['main']['App']['MoveImageOperation'](arg1, arg2);
}

export function OpenImageFileSelector() {
  return window['go']['main']['App']['OpenImageFileSelector']();
}

export function ProcessImage(arg1) {
  return window['go']['main']['App']['ProcessImage'](arg1);
}

export function RemoveImageOperationAtIndex(arg1) {
  return window['go']['main']['App']['RemoveImageOperationAtIndex'](arg1);
}

export function ReplaceImageOperationAtIndex(arg1, arg2) {
  return window['go']['main']['App']['ReplaceImageOperationAtIndex'](arg1, arg2);
}

export function ResetAppState() {
  return window['go']['main']['App']['ResetAppState']();
}

export function RotateImageBy90Deg() {
  return window['go']['main']['App']['RotateImageBy90Deg']();
}

export function SetOriginalImage(arg1) {
  return window['go']['main']['App']['SetOriginalImage'](arg1);
}

export function ToggleImageOperation(arg1, arg2) {
  return window['go']['main']['App']['ToggleImageOperation'](arg1, arg2);
}

export function UpdateImageOperationAtIndex(arg1, arg2) {
  return window['go']['main']['App']['UpdateImageOperationAtIndex'](arg1, arg2);
}
